spring:
  application:
    name: patient-service

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:patientSchema
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 9093